# Generated by Django 4.2 on 2023-05-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
