# Generated by Django 4.2 on 2023-05-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
