# Generated by Django 4.1.4 on 2023-08-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='watch.product')),
                ('feature_vector', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='feature_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
